Repository unb-mds/2025-1-Eletta, pull requests merged in 2025-07, with the labels that each got.

#109 feat: adiciona testes unitários para funções recentes (#108)
  App/tests/test_cliente.py
  App/tests/test_servidor.py
Labels: back end, prioridade alta, feature

#113 feat: implementa landing page (#110)
  Docs/Arquitetura.md
  Docs/Sobrenos.md
  Docs/assets/videos/VideoHost.mp4
  Docs/assets/videos/VideoVotante.mp4
  Docs/index.md
  mkdocs.yml
Labels: back end, concluído, feature

#114 feat: atualiza vídeos de exibição #110
  Docs/assets/videos/VideoHost.mp4
  Docs/assets/videos/VideoVotante.mp4
Labels: back end, prioridade alta, concluído, feature

#118 Corrigir refatorar limpar
  App/Eletta.py
  App/controlador/controller.py
  App/servidor/cliente.py
  App/servidor/servidor.py
  App/tests/test_banco_de_dados.py
  App/tests/test_cliente.py
  App/tests/test_servidor.py
  App/views/home.py
  App/views/host.py
  App/views/votante.py
  mkdocs.yml
Labels: tarefa, back end, concluído

#119 docs: melhora a descrição do projeto no README.md (#64)
  README.md
Labels: documentation, prioridade alta, concluído
