Repository unb-mds/2025-1-Eletta, pull requests merged in 2025-06, with the labels that each got.

#56 chore: testes unitários, formatação com Black/Ruff e CI configurado
  .github/workflows/ci.yml
  .github/workflows/pipeline-ci.yml
  .gitignore
  App/Eletta.py
  App/controlador/__pycache__/__init__.cpython-311.pyc
  App/controlador/__pycache__/controller.cpython-311.pyc
  App/controlador/controller.py
  App/servidor/Data_Base/DB.py
  App/servidor/Data_Base/__pycache__/DB.cpython-311.pyc
  App/servidor/Data_Base/__pycache__/__init__.cpython-311.pyc
  App/servidor/__pycache__/__init__.cpython-311.pyc
  App/servidor/__pycache__/cliente.cpython-311.pyc
  App/servidor/__pycache__/servidor.cpython-311.pyc
  App/servidor/cliente.py
  App/servidor/servidor.py
  App/tests/test_banco_de_dados.py
  App/tests/test_cliente.py
  App/tests/test_servidor.py
  App/views/__pycache__/__init__.cpython-311.pyc
  App/views/__pycache__/home.cpython-311.pyc
  App/views/__pycache__/host.cpython-311.pyc
  App/views/__pycache__/votante.cpython-311.pyc
  App/views/home.py
  App/views/host.py
  App/views/votante.py
  requirements.txt
Labels: back end

#58 implementação da feature de múltiplas pautas em uma mesma sessão
  App/Eletta.py
  App/controlador/controller.py
  App/servidor/Data_Base/dados.json
  App/servidor/cliente.py
  App/servidor/servidor.py
  App/views/home.py
  App/views/host.py
  App/views/votante.py
Labels: back end

#66 feat: tela de confirmação de voto e criação de sala
  App/Eletta.py
  App/controlador/controller.py
  App/views/host.py
  App/views/votante.py
Labels: front end, feature

#74 feat: implementar tela de espera pelo host
  App/Eletta.py
  App/controlador/controller.py
  App/views/votante.py
  Docs/Estudos/Versao_1_do_Prototipo/Votacao_APP/.idea/.gitignore
  Docs/Estudos/Versao_1_do_Prototipo/Votacao_APP/.idea/Votacao_APP.iml
  Docs/Estudos/Versao_1_do_Prototipo/Votacao_APP/.idea/caches/deviceStreaming.xml
  Docs/Estudos/Versao_1_do_Prototipo/Votacao_APP/.idea/misc.xml
  Docs/Estudos/Versao_1_do_Prototipo/Votacao_APP/.idea/modules.xml
  Docs/Estudos/Versao_1_do_Prototipo/Votacao_APP/README.md
  Docs/Estudos/Versao_1_do_Prototipo/Votacao_APP/chave_cripto.key
  Docs/Estudos/Versao_1_do_Prototipo/Votacao_APP/pyproject.toml
  Docs/Estudos/Versao_1_do_Prototipo/Votacao_APP/requirements.txt
  Docs/Estudos/Versao_1_do_Prototipo/Votacao_APP/src/Clientes.py
  Docs/Estudos/Versao_1_do_Prototipo/Votacao_APP/src/assets/icon.png
  Docs/Estudos/Versao_1_do_Prototipo/Votacao_APP/src/assets/splash_android.png
  Docs/Estudos/Versao_1_do_Prototipo/Votacao_APP/src/chave_cripto.key
  Docs/Estudos/Versao_1_do_Prototipo/Votacao_APP/src/main.py
  Docs/Estudos/Versao_1_do_Prototipo/Votacao_APP/src/painel.py
  Docs/Estudos/Versao_1_do_Prototipo/Votacao_APP/src/votos.json
  Docs/Estudos/Versao_1_do_Prototipo/Votacao_APP/votos.json
Labels: front end, prioridade média, concluído, feature

#80 ciração do time do cronometro, e correções.
  App/Eletta.py
  App/controlador/controller.py
  App/servidor/servidor.py
  App/views/host.py
  App/views/votante.py
Labels: back end, prioridade alta, concluído, feature

#91 Fix: Erro decremento cronômetro
  App/controlador/controller.py
  App/views/host.py
Labels: bug, front end, back end, prioridade alta, concluído

#89 Tela ja tem um host
  App/controlador/controller.py
  App/servidor/servidor.py
Labels: front end, back end, prioridade alta

#98 feat: Tela intermediaria para host ver o resultado primeiro e assim m…
  App/Eletta.py
  App/controlador/controller.py
  App/servidor/servidor.py
  App/views/host.py
Labels: front end, prioridade alta, concluído
